---
- name: "Install package"
  hosts: frontend
  become: yes
  tasks:
    - name: "Install Nginx"
      ansible.builtin.package:
        name: nginx
        state: present
  
    - name: "Start and Enable service"
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
