---
- name: "Multi Playbook Demo-Play 1"
  hosts: local
  connection: local
  tasks:
    - name: "Play1 Task1"
      ansible.builtin.debug:
        msg: "Message from Play1 Task1"

  
    - name: "Play1 Task2"
      ansible.builtin.debug:
        msg: "Message from Play1 Task2"


- name: "Multi Playbook Demo-Play2"
  hosts: local
  connection: local
  tasks:
    - name: "Play2 Task1"
      ansible.builtin.debug:
        msg: "Message from Play2 Task1"


    - name: "Play2 Task2"
      ansible.builtin.debug:
        msg: "Message from Play2 Task2"

