---
- name: Variable using user prompt
  hosts: local
  connection: local
  vars_prompt:
    - name: USERNAME
      prompt: What is your user name
      private: false

    - name: PASSWORD
      prompt: What is your password
      private: true

  tasks:
    - name: "Print user info"
      ansible.builtin.debug:
      msg: Your user name is USERNAME and password is PASSWORD
