---
- name: Variables from inventory files - part 2
  hosts: frontend
  tasks:
    - name: course info
      ansible.builtin.debug:
        msg: "course name: {{ COURSE }} duration: {{ DURATION }}, trainer: {{ TRAINER }}"