---
- name: check if package is installed
  hosts: frontend
  become: yes
  tasks:
    - name: check if package is installed on Linux 2 and 3
      ansible.builtin.debug:
        msg: "{{ ansible-facts.packages['nginx'] | length }} versions of the Nginx installed"
      when: "'nginx' in ansible-facts.packages"
