---
- name: loops demo
  hosts: local
  connection: local
  tasks:
    - name: print names
      ansible.builtin.debug:
        msg: " hi {{ item }}, how are you today"
      loop:
        - rudroju
        - shyam
        - prasad

