---
- name: ansible functions demo
  hosts: local
  connection: local
  vars:
    person_name: shyam
  tasks:
    - name: print name
      ansible.builtin.debug:
        msg: "hi {{ person_name }}"
  

